server:
  port: 8080
spring:
  application:
    name: "CrediYa"
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  datasource:
    initialization-mode: "always"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: autentication_db
    schema: public
    username: postgres
    password: 1234
