server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: "CrediYa"
  main:
    web-application-type: reactive

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:36000000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "https://tudominio.com,https://<ALB-DNS>"

adapters:
  r2dbc:
    host: ${R2DBC_HOST}
    port: ${R2DBC_PORT}
    database: ${R2DBC_DATABASE}
    schema: ${R2DBC_SCHEMA}
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}